spring:
  application:
    name: rfs-zuul

server:
  port: 9000

zuul:
  routes:
    rfs-service-login:
      path: /api/login/**
      serviceId: rfs-service-login
    rfs-service-admin:
      path: /api/admin/**
      serviceId: rfs-service-admin