spring:
  application:
    name: rfs-zuul

server:
  port: 9003

zuul:
  routes:
    api-service-login:
      path: /api/login/**
      serviceId: rfs-service-login
    api-service-admin:
      path: /api/admin/**
      serviceId: rfs-service-admin