spring:
  application:
    name: rfs-service-redis

  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: 192.168.1.130:26379, 192.168.1.130:26380, 192.168.1.130:26381
server:
  port: 10003