spring:
  application:
    name: rfs-service-admin
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.130:3307/rfs-admin?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

server:
  port: 10004

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.vada.rfs.service.admin.domain
##日志 设置mybatis的sql语句打印到控制台
logging:
  level:
    com.vada.rfs.service.admin.mapper: trace
    io.swagger.models.parameters.AbstractSerializableParameter: error

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://192.168.1.129:10001/oauth/token
      user-authorization-uri: http://192.168.1.129:10001/oauth/authorize
    resource:
      token-info-uri: http://192.168.1.129:10001/oauth/check_token